plugins {
    alias(libs.plugins.quarkus)
}

dependencies {
    implementation(enforcedPlatform(libs.quarkus.bom))

    implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-rest-jackson")
    implementation("io.quarkus:quarkus-smallrye-openapi")
    implementation("io.quarkus:quarkus-container-image-jib")

    // iceberg
    implementation(project(":modules:api:api-iceberg"))
    implementation(project(':modules:catalog:catalog-iceberg-core'))
    implementation(project(':modules:catalog:catalog-iceberg-hadoop'))
//    implementation(project(':modules:catalog:catalog-iceberg-hive')) // fixme
    implementation(project(':modules:catalog:catalog-iceberg-inmemory'))
    implementation(project(':modules:catalog:catalog-iceberg-jdbc'))
    implementation(project(':modules:catalog:catalog-iceberg-kasanari'))
    implementation(project(':modules:catalog:catalog-iceberg-nessie'))
    implementation(project(':modules:catalog:catalog-iceberg-rest'))

    testImplementation("io.quarkus:quarkus-junit5")
    testImplementation("io.rest-assured:rest-assured")
}

test {
    useJUnitPlatform()
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}