---
openapi: 3.0.3
info:
  title: Kasanari Lance REST Catalog API
  version: 0.0.1

servers:
  - url: "{scheme}://{host}/{basePath}"
    description: Server URL when the port can be inferred from the scheme
    variables:
      scheme:
        description: The scheme of the URI, either http or https.
        default: https
      host:
        description: The host address for the specified server
        default: localhost
      basePath:
        description: Optional prefix to be appended to all routes
        default: ""
  - url: "{scheme}://{host}:{port}/{basePath}"
    description: Generic base server URL, with all parts configurable
    variables:
      scheme:
        description: The scheme of the URI, either http or https.
        default: https
      host:
        description: The host address for the specified server
        default: localhost
      port:
        description: The port used when addressing the host
        default: "443"
      basePath:
        description: Optional prefix to be appended to all routes
        default: ""

security:
  - OAuth2: []
  - BearerAuth: []

paths:

  ##########################
  # Lance REST Catalog API #
  # Metadata operations + CreateTable / DeclareTable (createEmptyTable)
  # '~1' -> replacement for '/'
  ##########################

  /lance/v1/namespace/{id}/create:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1namespace~1{id}~1create'

  /lance/v1/namespace/{id}/list:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1namespace~1{id}~1list'

  /lance/v1/namespace/{id}/describe:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1namespace~1{id}~1describe'

  /lance/v1/namespace/{id}/drop:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1namespace~1{id}~1drop'

  /lance/v1/namespace/{id}/exists:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1namespace~1{id}~1exists'

  /lance/v1/namespace/{id}/table/list:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1namespace~1{id}~1table~1list'

  /lance/v1/table/{id}/create:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1create'

  /lance/v1/table/{id}/register:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1register'

  /lance/v1/table/{id}/describe:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1describe'

  /lance/v1/table/{id}/exists:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1exists'

  /lance/v1/table/{id}/drop:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1drop'

  /lance/v1/table/{id}/deregister:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1deregister'

  /lance/v1/table/{id}/restore:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1restore'

  /lance/v1/table/{id}/rename:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1rename'

  /lance/v1/table/{id}/alter_columns:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1alter_columns'

  /lance/v1/table/{id}/drop_columns:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1drop_columns'

  /lance/v1/table/{id}/add_columns:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1add_columns'

  /lance/v1/table/{id}/declare:
    $ref: './lance-openapi-0.7.2.yaml#/paths/~1v1~1table~1{id}~1declare'

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description:
        This scheme is used for OAuth2 authorization.
      flows:
        clientCredentials:
          tokenUrl: /lance/v1/oauth/tokens
          scopes: {}
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
