plugins {
    // https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/README.adoc
    alias(libs.plugins.openapi.generator)
    alias(libs.plugins.jandex)
}

dependencies {
    implementation libs.iceberg.api
    implementation libs.iceberg.core
    implementation libs.iceberg.common

    implementation(libs.jakarta.annotation.api)
    implementation(libs.jakarta.inject.api)
    implementation(libs.jakarta.ws.rs.api)
}

openApiValidate {
    inputSpec.set("$projectDir/src/main/resources/openapi/openapi.yaml")
}

var rootDir = rootProject.layout.projectDirectory
var specsDir = rootDir.dir("spec")
var icebergSpecDir = specsDir.dir("iceberg")
var templatesDir = icebergSpecDir.dir("server-templates")
var generatedDir = project.layout.buildDirectory.dir("generated")
var generatedOpenApiSrcDir = project.layout.buildDirectory.dir("generated/src/main/java")

// https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/jaxrs-resteasy.md
// https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin
openApiGenerate {
    inputSpec = icebergSpecDir.file("kasanari-catalog-service.yaml").asFile.absolutePath
    generatorName = "jaxrs-resteasy"
    outputDir = generatedDir.get().asFile.absolutePath
    ignoreFileOverride = specsDir.file(".openapi-generator-ignore").asFile.absolutePath
    removeOperationIdPrefix = true
    // https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy
    templateDir = templatesDir.asFile.absolutePath

    globalProperties.put("apiDocs", "false")
    globalProperties.put("models", "false")
    globalProperties.put("apis", "CatalogApi,ConfigurationApi")
    globalProperties.put("modelTests", "false")

    serverVariables.put("basePath", "api/catalog")

    configOptions.put("resourceName", "catalog")
    configOptions.put("useTags", "true")
    configOptions.put("useBeanValidation", "false")
    configOptions.put("sourceFolder", "src/main/java")
    configOptions.put("useJakartaEe", "true")
    configOptions.put("hideGenerationTimestamp", "true")

    additionalProperties.put("apiNamePrefix", "IcebergRest")
    additionalProperties.put("apiNameSuffix", "")
    additionalProperties.put("apiPackage", "kasanari.catalog.iceberg.api")
    additionalProperties.put("dateLibrary", "java8")

    var modelNameMap = new HashMap<String, String>()
    modelNameMap.put("CatalogConfig", "org.apache.iceberg.rest.responses.ConfigResponse")
    modelNameMap.put("LoadTableResult", "org.apache.iceberg.rest.responses.LoadTableResponse")
    modelNameMap.put("LoadViewResult", "org.apache.iceberg.rest.responses.LoadViewResponse")
    modelNameMap.put("CommitTableResponse", "org.apache.iceberg.rest.responses.LoadTableResponse")
    modelNameMap.put("CommitViewRequest", "org.apache.iceberg.rest.requests.UpdateTableRequest")
    modelNameMap.put("CommitTableRequest", "org.apache.iceberg.rest.requests.UpdateTableRequest")
    modelNameMap.put("IcebergErrorResponse", "org.apache.iceberg.rest.responses.ErrorResponse")

    modelNameMappings = modelNameMap

    var importMap = new HashMap<String, String>()
    importMap.put("CatalogConfig", "org.apache.iceberg.rest.responses.ConfigResponse")
    importMap.put("CommitTableResponse", "org.apache.iceberg.rest.responses.LoadTableResponse")
    importMap.put("CreateNamespaceRequest", "org.apache.iceberg.rest.requests.CreateNamespaceRequest")
    importMap.put("CreateNamespaceResponse", "org.apache.iceberg.rest.responses.CreateNamespaceResponse")
    importMap.put("CreateTableRequest", "org.apache.iceberg.rest.requests.CreateTableRequest")
    importMap.put("ErrorModel", "org.apache.iceberg.rest.responses.ErrorResponse")
    importMap.put("GetNamespaceResponse", "org.apache.iceberg.rest.responses.GetNamespaceResponse")
    importMap.put("ListNamespacesResponse", "org.apache.iceberg.rest.responses.ListNamespacesResponse")
    importMap.put("ListTablesResponse", "org.apache.iceberg.rest.responses.ListTablesResponse")
    importMap.put("LoadCredentialsResponse", "org.apache.iceberg.rest.responses.LoadCredentialsResponse")
    importMap.put("LoadTableResult", "org.apache.iceberg.rest.responses.LoadTableResponse")
    importMap.put("LoadViewResult", "org.apache.iceberg.rest.responses.LoadTableResponse")
    importMap.put("OAuthTokenResponse", "org.apache.iceberg.rest.responses.OAuthTokenResponse")
    importMap.put("OAuthErrorResponse", "org.apache.iceberg.rest.responses.OAuthErrorResponse")
    importMap.put("RenameTableRequest", "org.apache.iceberg.rest.requests.RenameTableRequest")
    importMap.put("ReportMetricsRequest", "org.apache.iceberg.rest.requests.ReportMetricsRequest")
    importMap.put("UpdateNamespacePropertiesRequest", "org.apache.iceberg.rest.requests.UpdateNamespacePropertiesRequest")
    importMap.put("UpdateNamespacePropertiesResponse", "org.apache.iceberg.rest.responses.UpdateNamespacePropertiesResponse")
    importMap.put("CommitTransactionRequest", "org.apache.iceberg.rest.requests.CommitTransactionRequest")
    importMap.put("CreateViewRequest", "org.apache.iceberg.rest.requests.CreateViewRequest")
    importMap.put("RegisterTableRequest", "org.apache.iceberg.rest.requests.RegisterTableRequest")
    importMap.put("IcebergErrorResponse", "org.apache.iceberg.rest.responses.ErrorResponse")
    importMap.put("OAuthError", "org.apache.iceberg.rest.responses.ErrorResponse")
    importMap.put("CommitViewRequest", "org.apache.iceberg.rest.requests.UpdateTableRequest")
    importMap.put("CommitTableRequest", "org.apache.iceberg.rest.requests.UpdateTableRequest")

    importMappings = importMap
}

sourceSets {
    main {
        java {
            srcDir(generatedOpenApiSrcDir)
        }
    }
}

tasks.openApiGenerate {
    doLast {
        delete(files("${buildDir}/generated/src/main/java/kasanari/catalog/iceberg/api/impl"),)
    }
}

tasks.compileJava {
    dependsOn(tasks.openApiGenerate)
}