services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    ports:
      - "9030:9000"
      - "9031:9001"
    command: ["server", "/data", "--console-address", ":9001"]

  mc:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "

  catalog-storage:
    image: postgres:17
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  kasanari:
    image: ${KASANARI_IMAGE:-local/kasanari:0.1.0}
    depends_on:
      - catalog-storage
      - minio
      - mc
    ports:
      - "9093:9090"
    environment:
      JVM_OPTS: >-
        -Dkasanari.management.metadata.jdbc-properties."kasanari.jdbc.user"=postgres
        -Dkasanari.management.metadata.jdbc-properties."kasanari.jdbc.password"=postgres
        -Dkasanari.management.metadata.jdbc-properties."uri"=jdbc:postgresql://catalog-storage:5432/postgres
        -Dkasanari.authentication.type=none

  flink:
    image: apache/flink:1.19.2-scala_2.12-java17
    depends_on:
      - kasanari
    command: ["bash", "-lc", "tail -f /dev/null"]
    volumes:
      - ./notebooks:/workspace/notebooks
