plugins {
    id 'java'
}

allprojects {
    group 'kasanari'
    version '0.1.0'

    repositories {
        mavenCentral()
        mavenLocal()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'java-library'

    java {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    test {
        useJUnitPlatform()
    }

    compileJava {
        options.encoding = 'UTF-8'
        options.compilerArgs << '-parameters'
    }

    compileTestJava {
        options.encoding = 'UTF-8'
    }
}
//
//tasks.compileJava {
//    doLast {
//        tasks.findByPath("api:api-iceberg:cleanupCodeGeneration")
//        tasks.findByPath("api:api-paimon:cleanupCodeGeneration")
//        println("Deleted RestApplication & RestResourceRoot")
//    }
//}

