services:
  minio:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"
      - "9001:9001"
    command: [ "server", "/data", "--console-address", ":9001" ]

  mc:
    image: minio/minio:RELEASE.2025-02-28T09-55-16Z
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      tail -f /dev/null
      "

  catalog-storage:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  kasanari:
    image: ${KASANARI_IMAGE:-local/kasanari:0.1.0}
    depends_on:
      - catalog-storage
      - mc
    ports:
      - "9090:9090"
    environment:
      JVM_OPTS: >-
        -Dkasanari.management.metadata.jdbc-properties."kasanari.jdbc.user"=postgres
        -Dkasanari.management.metadata.jdbc-properties."kasanari.jdbc.password"=postgres
        -Dkasanari.management.metadata.jdbc-properties."uri"=jdbc:postgresql://catalog-storage:5432/postgres
        -Dkasanari.authentication.type=none
        -Dkasanari.authorization.type=allow-all

  spark-notebook:
    image: nryanov/tools-jupyter:sha-3ceec6971fe0c32c13fa9fa83e40f80d6251e648
    depends_on:
      - kasanari
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: kasanari
      KASANARI_BASE_URL: http://kasanari:9090
      KASANARI_S3_ENDPOINT: http://minio:9000
      KASANARI_JDBC_URI: jdbc:postgresql://catalog-storage:5432/postgres
      AWS_REGION: none
    volumes:
      - ./:/home/jovyan/work
