dependencies {
    implementation project(':modules:catalog:catalog-iceberg-core')
    implementation libs.iceberg.hive
    implementation libs.hadoop3.client.api
    implementation libs.hadoop3.client.runtime
    implementation libs.hive.metastore
    implementation libs.hive.common

    testImplementation libs.testcontainers.core
    testImplementation testFixtures(project(':modules:catalog:catalog-iceberg-core'))
}