services:
  catalog-storage:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 20

  kasanari:
    image: nryanov/kasanari:v0.1.0
    depends_on:
      catalog-storage:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      SPI_EXT_DIR: /opt/kasanari/spi
      JVM_OPTS: >-
        -Dkasanari.management.metadata.jdbc-properties."kasanari.jdbc.user"=postgres
        -Dkasanari.management.metadata.jdbc-properties."kasanari.jdbc.password"=postgres
        -Dkasanari.management.metadata.jdbc-properties."uri"=jdbc:postgresql://catalog-storage:5432/postgres
        -Dkasanari.authentication.type=header-token
        -Dkasanari.authentication.header-token.secret=dev-secret
        -Dkasanari.authentication.header-token.header=X-Kasanari-Token
      AWS_REGION: none
    volumes:
      - ../authentication/build/libs/auth-custom-example.jar:/opt/kasanari/spi/auth-custom-example.jar:ro
