[versions]
openapi-generator = "7.14.0"
quarkus = "3.31.2"
jandex = "1.0.0"
iceberg = "1.10.1"
paimon = "1.3.1"
hadoop3 = "3.4.1"
awssdk = "2.41.24"
hive = { strictly = "2.3.9" }
slfj4 = "2.0.17"
jdbi = "3.49.4"
agroal = "2.7.1"

jakarta-ws-rs-api = "4.0.0"
jakarta-inject-api = "2.0.1"
jakarta-annotations-api = "3.0.0"
# test dependencies
junit = "5.12.2"
junit-platform = "1.12.2"
testcontainers = "1.21.0"
testcontainers-nessie = "0.104.1"
logback = "1.5.18"
jdbc-postgresql = "42.7.5"


[libraries]
quarkus-bom = { group = "io.quarkus.platform", name = "quarkus-bom", version.ref = "quarkus" }

# openapi generation
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotations-api" }
jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject-api" }
jakarta-ws-rs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "jakarta-ws-rs-api" }

# iceberg
# todo: use bom instead of direct deps
iceberg-bom = { group = "org.apache.iceberg", name = "iceberg-bom", version.ref = "iceberg" }
iceberg-core = { group = "org.apache.iceberg", name = "iceberg-core", version.ref = "iceberg" }
iceberg-api = { group = "org.apache.iceberg", name = "iceberg-api", version.ref = "iceberg" }
iceberg-common = { group = "org.apache.iceberg", name = "iceberg-common", version.ref = "iceberg" }
iceberg-nessie = { group = "org.apache.iceberg", name = "iceberg-nessie", version.ref = "iceberg" }
iceberg-hive = { group = "org.apache.iceberg", name = "iceberg-hive-runtime", version.ref = "iceberg" }
iceberg-aws = { group = "org.apache.iceberg", name = "iceberg-aws", version.ref = "iceberg" }

# paimon
paimon-api = { group = "org.apache.paimon", name = "paimon-api", version.ref = "paimon" }

hadoop3-client-api = { group = "org.apache.hadoop", name = "hadoop-client-api", version.ref = "hadoop3"}
hadoop3-client-runtime = { group = "org.apache.hadoop", name = "hadoop-client-runtime", version.ref = "hadoop3"}
hadoop3-common = { group = "org.apache.hadoop", name = "hadoop-common", version.ref = "hadoop3"}
hadoop3-aws = { group = "org.apache.hadoop", name = "hadoop-aws", version.ref = "hadoop3"}
hadoop3-hdfs-client = { module = "org.apache.hadoop:hadoop-hdfs-client", version.ref = "hadoop3" }

awssdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "awssdk" }

hive-metastore = { group = "org.apache.hive", name = "hive-metastore", version.ref = "hive" }
hive-common = { group = "org.apache.hive", name = "hive-common", version.ref = "hive" }

jdbi-core = { group = "org.jdbi", name = "jdbi3-core", version.ref = "jdbi" }
agroal-pool = { group = "io.agroal", name = "agroal-pool", version.ref = "agroal" }

slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slfj4" }
logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# test dependencies
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }

testcontainers-core = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers" }
testcontainers-minio = { group = "org.testcontainers", name = "minio", version.ref = "testcontainers" }
testcontainers-nessie = { group = "org.projectnessie.nessie", name = "nessie-nessie-testcontainer", version.ref = "testcontainers-nessie" }

jdbc-postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "jdbc-postgresql" }

[plugins]
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
jandex = { id = "org.kordamp.gradle.jandex", version.ref = "jandex" }
