[versions]
openapi-generator = "7.12.0"
quarkus = "3.15.1"
jandex = "1.0.0"
iceberg = "1.7.1"
# test dependencies
junit = "5.12.2"
junit-platform = "1.12.2"
testcontainers = "1.21.0"


[libraries]
quarkus-bom = { group = "io.quarkus.platform", name = "quarkus-bom", version.ref = "quarkus" }
quarkus-jackson = { group = "io.quarkus", name = "quarkus-rest-jackson" }
quarkus-openapi = { group = "io.quarkus", name = "quarkus-smallrye-openapi" }

iceberg-core = { group = "org.apache.iceberg", name = "iceberg-core", version.ref = "iceberg" }
iceberg-nessie = { group = "org.apache.iceberg", name = "iceberg-nessie", version.ref = "iceberg" }
iceberg-hive = { group = "org.apache.iceberg", name = "iceberg-hive-runtime", version.ref = "iceberg" }

# test dependencies
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit-platform" }

testcontainers-core = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers" }
testcontainers-postgresql = { group = "org.testcontainers", name = "postgresql", version.ref = "testcontainers" }
testcontainers-minio = { group = "org.testcontainers", name = "minio", version.ref = "testcontainers" }

[plugins]
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
jandex = { id = "org.kordamp.gradle.jandex", version.ref = "jandex" }
