[versions]
openapi-generator = "7.14.0"
quarkus = "3.31.2"
jandex = "1.0.0"
iceberg = "1.10.1"
paimon = "1.4.1"
lance = "6.0.0"
lance-namespace = "0.7.2"
hadoop3 = "3.4.1"
awssdk = "2.41.24"
hive = { strictly = "2.3.9" }
slfj4 = "2.0.17"
jdbi = "3.49.4"
agroal = "2.7.1"
jcasbin = "1.99.0"
jackson = "2.20.1"
jakarta-ws-rs-api = "4.0.0"
jakarta-inject-api = "2.0.1"
jakarta-annotations-api = "3.0.0"
jdbc-postgresql = "42.7.5"
smallrye = "2.9.4"
# test dependencies
junit = "6.1.1"
testcontainers = "1.21.0"
testcontainers-nessie = "0.104.1"
logback = "1.5.18"


[libraries]
quarkus-bom = { group = "io.quarkus.platform", name = "quarkus-bom", version.ref = "quarkus" }

# openapi generation
jakarta-annotation-api = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotations-api" }
jakarta-inject-api = { module = "jakarta.inject:jakarta.inject-api", version.ref = "jakarta-inject-api" }
jakarta-ws-rs-api = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "jakarta-ws-rs-api" }

# jackson
jackson-bom = { group = "com.fasterxml.jackson", name = "jackson-bom", version.ref = "jackson" }

# iceberg
# todo: use bom instead of direct deps
iceberg-platform = { group = "org.apache.iceberg", name = "iceberg-bom", version.ref = "iceberg" }
# for iceberg-api module only
iceberg-core = { group = "org.apache.iceberg", name = "iceberg-core", version.ref = "iceberg" }
iceberg-api = { group = "org.apache.iceberg", name = "iceberg-api", version.ref = "iceberg" }
iceberg-common = { group = "org.apache.iceberg", name = "iceberg-common", version.ref = "iceberg" }
iceberg-aws = { group = "org.apache.iceberg", name = "iceberg-aws", version.ref = "iceberg" }

# paimon
paimon-api = { group = "org.apache.paimon", name = "paimon-api", version.ref = "paimon" }
paimon-core = { group = "org.apache.paimon", name = "paimon-core", version.ref = "paimon" }
paimon-common = { group = "org.apache.paimon", name = "paimon-common", version.ref = "paimon" }
paimon-s3 = { group = "org.apache.paimon", name = "paimon-s3", version.ref = "paimon" }
paimon-format = { group = "org.apache.paimon", name = "paimon-format", version.ref = "paimon" }
paimon-hive-catalog = { group = "org.apache.paimon", name = "paimon-hive-catalog", version.ref = "paimon" }

# lance
# https://mvnrepository.com/artifact/org.lance
lance-core = { group = "org.lance", name = "lance-core", version.ref = "lance" }
lance-namespace-core = { group = "org.lance", name = "lance-namespace-core", version.ref = "lance-namespace" }

hadoop3-client = { group = "org.apache.hadoop", name = "hadoop-client", version.ref = "hadoop3" }
hadoop3-common = { group = "org.apache.hadoop", name = "hadoop-common", version.ref = "hadoop3"}
hadoop3-aws = { group = "org.apache.hadoop", name = "hadoop-aws", version.ref = "hadoop3"}

aws-platform = { module = "software.amazon.awssdk:bom", version.ref = "awssdk" }
awssdk-bom = { module = "software.amazon.awssdk:bom", version.ref = "awssdk" }

hive-metastore = { group = "org.apache.hive", name = "hive-metastore", version.ref = "hive" }

jdbi-core = { group = "org.jdbi", name = "jdbi3-core", version.ref = "jdbi" }
agroal-pool = { group = "io.agroal", name = "agroal-pool", version.ref = "agroal" }
casbin-jcasbin = { group = "org.casbin", name = "jcasbin", version.ref = "jcasbin" }

slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slfj4" }
jdbc-postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "jdbc-postgresql" }

smallrye-mutiny = { group = "io.smallrye.reactive", name = "mutiny", version.ref = "smallrye" }

# test dependencies
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
testcontainers-bom = { group = "org.testcontainers", name = "testcontainers-bom", version.ref = "testcontainers" }
testcontainers-nessie = { group = "org.projectnessie.nessie", name = "nessie-nessie-testcontainer", version.ref = "testcontainers-nessie" }

logback = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

[plugins]
openapi-generator = { id = "org.openapi.generator", version.ref = "openapi-generator" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
jandex = { id = "org.kordamp.gradle.jandex", version.ref = "jandex" }
