dependencies {
    api libs.iceberg.aws

    api(libs.hadoop3.common) {
        exclude group: "org.slf4j", module: "slf4j-reload4j"
        exclude group: "org.slf4j", module: "slf4j-log4j12"
        exclude group: "ch.qos.reload4j", module: "reload4j"
        exclude group: "log4j", module: "log4j"
        exclude group: "org.apache.zookeeper", module: "zookeeper"
        exclude group: "org.apache.hadoop.thirdparty", module: "hadoop-shaded-protobuf_3_25"
        exclude group: "com.github.pjfanning", module: "jersey-json"
        exclude group: "com.sun.jersey", module: "jersey-core"
        exclude group: "com.sun.jersey", module: "jersey-server"
        exclude group: "com.sun.jersey", module: "jersey-servlet"
        exclude group: "com.sun.jersey", module: "jersey-servlet"
        exclude group: "io.dropwizard.metrics", module: "metrics-core"
    }
    api(libs.hadoop3.aws) {
        exclude group: "software.amazon.awssdk", module: "bundle"
    }

    api libs.hadoop3.hdfs.client
    api libs.hadoop3.client.api

    api platform(libs.awssdk.bom)
    api "software.amazon.awssdk:sts"
    api "software.amazon.awssdk:iam-policy-builder"
    api "software.amazon.awssdk:s3"
    api "software.amazon.awssdk:aws-core"
    api "software.amazon.awssdk:sdk-core"
    api "software.amazon.awssdk:regions"
    api "software.amazon.awssdk:auth"
    api "software.amazon.awssdk:s3-transfer-manager"


//    amazon-http-auth = { group = "software.amazon.awssdk", name = "http-auth", version.ref = "s3" }
//    amazon-http-auth-aws = { group = "software.amazon.awssdk", name = "http-auth-aws", version.ref = "s3" }
//    amazon-netty-nio-client = { group = "software.amazon.awssdk", name = "netty-nio-client", version.ref = "s3" }
}