####### QUARKUS SPECIFIC CONFIGS #######
quarkus.swagger-ui.always-include=false

quarkus.http.port=9090
quarkus.devservices.enabled=false

management.metadata.jdbc-properties."kasanari.jdbc.user"=postgres
management.metadata.jdbc-properties."kasanari.jdbc.password"=postgres
management.metadata.jdbc-properties."uri"=jdbc:postgresql://localhost:5432/postgres

#kasanari.authentication.type=none
kasanari.authentication.type=ldap
kasanari.authentication.ldap.url=ldap://localhost:389
kasanari.authentication.ldap.bind-principal=cn=admin,dc=kasanari,dc=local
kasanari.authentication.ldap.bind-password=admin
kasanari.authentication.ldap.search-base-dn=ou=users,dc=kasanari,dc=local
kasanari.authentication.ldap.rdn-identifier=uid


#kasanari.authentication.type=oidc
#kasanari.authentication.oidc.issuer-url=http://localhost:8080/realms/kasanari
#kasanari.authentication.oidc.client-id=kasanari-api
#kasanari.authentication.oidc.client-secret=change-me


#kasanari.authorization.type=casbin
#kasanari.authorization.casbin.superuser-subjects=root,admin
#kasanari.authorization.casbin.jdbc.user=postgres
#kasanari.authorization.casbin.jdbc.password=postgres
#kasanari.authorization.casbin.jdbc.uri=jdbc:postgresql://localhost:5432/postgres