####### QUARKUS SPECIFIC CONFIGS #######
quarkus.swagger-ui.always-include=false

quarkus.http.port=9090
quarkus.devservices.enabled=false

management.metadata.jdbc-properties."kasanari.jdbc.user"=postgres
management.metadata.jdbc-properties."kasanari.jdbc.password"=postgres
management.metadata.jdbc-properties."uri"=jdbc:postgresql://localhost:5432/postgres
