####### QUARKUS SPECIFIC CONFIGS #######
quarkus.swagger-ui.always-include=false

quarkus.http.port=9090
quarkus.devservices.enabled=false

management.metadata.jdbc-properties."kasanari.jdbc.user"=postgres
management.metadata.jdbc-properties."kasanari.jdbc.password"=postgres
management.metadata.jdbc-properties."uri"=jdbc:postgresql://localhost:5432/postgres

kasanari.auth.type=none

#kasanari.auth.type=ldap
#kasanari.auth.ldap.url=ldap://localhost:389
#kasanari.auth.ldap.bind-principal=cn=admin,dc=kasanari,dc=local
#kasanari.auth.ldap.bind-password=admin
#kasanari.auth.ldap.search-base-dn=ou=users,dc=kasanari,dc=local
#kasanari.auth.ldap.rdn-identifier=uid

#kasanari.auth.type=oidc
#kasanari.auth.oidc.issuer-url=http://localhost:8080/realms/kasanari
#kasanari.auth.oidc.client-id=kasanari-api
#kasanari.auth.oidc.client-secret=change-me
