####### QUARKUS SPECIFIC CONFIGS #######
# required by ldap
quarkus.naming.enable-jndi=true
quarkus.http.port=9090

####### FOR SPI #######
quarkus.package.jar.type=legacy-jar
quarkus.container-image.group=local
quarkus.container-image.tag=latest
quarkus.container-image.build=false
quarkus.container-image.push=false

quarkus.jib.ports=9090

default.jvm.opts=-Xms1024m -Xmx2048m
jvm.opts=${JVM_OPTS:${default.jvm.opts}}
quarkus.jib.environment-variables."JVM_OPTS"=${jvm.opts}
quarkus.jib.environment-variables."APP_MAIN_CLASS"=${app.main.class:}
quarkus.jib.jvm-entrypoint=/bin/sh,/work/docker-entrypoint.sh
quarkus.container-image.name=kasanari
app.main.class=kasanari.server.bootstrap.Application


# Management metadata storage
kasanari.management.metadata.jdbc-properties."kasanari.jdbc.user"=postgres
kasanari.management.metadata.jdbc-properties."kasanari.jdbc.password"=postgres
kasanari.management.metadata.jdbc-properties."uri"=jdbc:postgresql://localhost:5432/postgres

smallrye.config.mapping.validate-unknown=false
# Authentication: none (default) | ldap | oidc | custom SPI type
kasanari.authentication.type=none
# Authorization: allow-all (default) | casbin | custom SPI type
# kasanari.authorization.type=allow-all
kasanari.catalog.refresh-interval=30s
