####### QUARKUS SPECIFIC CONFIGS #######
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/docs

# required by ldap
quarkus.naming.enable-jndi=true
quarkus.http.port=9090

quarkus.container-image.group=local
quarkus.container-image.name=application
quarkus.container-image.tag=latest
quarkus.container-image.build=true
quarkus.container-image.push=false

# uncomment if build for arm
# quarkus.jib.platforms=linux/arm64/v8

# Management metadata storage
management.metadata.jdbc-properties."kasanari.jdbc.user"=postgres
management.metadata.jdbc-properties."kasanari.jdbc.password"=postgres
management.metadata.jdbc-properties."uri"=jdbc:postgresql://localhost:5432/postgres

smallrye.config.mapping.validate-unknown=false
# Authentication: none (default) | ldap | oidc | custom SPI type
kasanari.authentication.type=none
# Authorization: allow-all (default) | casbin | custom SPI type
# kasanari.authorization.type=allow-all
kasanari.catalog.refresh-interval=30s
