dependencies {
    implementation project(':modules:catalog:catalog-iceberg-core')
    implementation libs.hadoop3.client.api
    implementation libs.hadoop3.client.runtime

    testImplementation libs.jdbc.postgresql
    testImplementation libs.testcontainers.postgresql
    testImplementation testFixtures(project(':modules:catalog:catalog-iceberg-core'))

//    S3 test

    implementation("org.apache.iceberg:iceberg-aws")
    implementation(platform(libs.awssdk.bom))
    implementation("software.amazon.awssdk:sts")
    implementation("software.amazon.awssdk:iam-policy-builder")
    implementation("software.amazon.awssdk:s3")
    implementation libs.iceberg.aws
//
    implementation(libs.hadoop3.common) {
//        exclude group: "org.slf4j", module: "slf4j-reload4j"
//        exclude group: "org.slf4j", module: "slf4j-log4j12"
//        exclude group: "ch.qos.reload4j", module: "reload4j"
//        exclude group: "log4j", module: "log4j"
//        exclude group: "org.apache.zookeeper", module: "zookeeper"
//        exclude group: "org.apache.hadoop.thirdparty", module: "hadoop-shaded-protobuf_3_25"
//        exclude group: "com.github.pjfanning", module: "jersey-json"
//        exclude group: "com.sun.jersey", module: "jersey-core"
//        exclude group: "com.sun.jersey", module: "jersey-server"
//        exclude group: "com.sun.jersey", module: "jersey-servlet"
//        exclude group: "com.sun.jersey", module: "jersey-servlet"
//        exclude group: "io.dropwizard.metrics", module: "metrics-core"
    }
    implementation(libs.hadoop3.aws) {
//        exclude group: "software.amazon.awssdk", module: "bundle"
    }

//    implementation libs.hadoop3.hdfs.client
//    implementation libs.hadoop3.client.api
//
//    implementation platform(libs.awssdk.bom)
//    implementation "software.amazon.awssdk:sts"
//    implementation "software.amazon.awssdk:iam-policy-builder"
//    implementation "software.amazon.awssdk:s3"
//    implementation "software.amazon.awssdk:aws-core"
//    implementation "software.amazon.awssdk:sdk-core"
//    implementation "software.amazon.awssdk:regions"
//    implementation "software.amazon.awssdk:auth"
//    implementation "software.amazon.awssdk:s3-transfer-manager"
}