dependencies {
    implementation project(':modules:catalog:catalog-iceberg-core')
    implementation libs.hadoop3.client.api
    implementation libs.hadoop3.client.runtime

    testImplementation libs.jdbc.postgresql
    testImplementation libs.testcontainers.postgresql
    testImplementation testFixtures(project(':modules:catalog:catalog-iceberg-core'))
}