plugins {
    // https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator-gradle-plugin/README.adoc
    alias(libs.plugins.openapi.generator)
    alias(libs.plugins.jandex)
}

dependencies {
    implementation libs.paimon.api
}

var rootDir = rootProject.layout.projectDirectory
var specsDir = rootDir.dir("spec")
var paimonSpecDir = specsDir.dir("paimon")
var templatesDir = paimonSpecDir.dir("server-templates")
var generatedDir = project.layout.buildDirectory.dir("generated")
var generatedOpenApiSrcDir = project.layout.buildDirectory.dir("generated/src/main/java")

// https://github.com/OpenAPITools/openapi-generator/blob/master/docs/generators/jaxrs-resteasy.md
// https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin
openApiGenerate {
    inputSpec = paimonSpecDir.file("paimon-openapi-1.0.0.yaml").asFile.absolutePath
    generatorName = "jaxrs-resteasy"
    outputDir = generatedDir.get().asFile.absolutePath
    ignoreFileOverride = specsDir.file(".openapi-generator-ignore").asFile.absolutePath
    removeOperationIdPrefix = true
    // https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator/src/main/resources/JavaJaxRS/resteasy
    templateDir = templatesDir.asFile.absolutePath

    globalProperties.put("apiDocs", "false")
    globalProperties.put("models", "false")
    globalProperties.put("apis", "")
    globalProperties.put("modelTests", "false")

    serverVariables.put("basePath", "api/catalog")

    configOptions.put("resourceName", "catalog")
    configOptions.put("useTags", "true")
    configOptions.put("useBeanValidation", "false")
    configOptions.put("sourceFolder", "src/main/java")
    configOptions.put("useJakartaEe", "true")
    configOptions.put("hideGenerationTimestamp", "true")

    additionalProperties.put("apiNamePrefix", "PaimonRest")
    additionalProperties.put("apiNameSuffix", "")
    additionalProperties.put("apiPackage", "kasanari.catalog.paimon.api")
    additionalProperties.put("dateLibrary", "java8")

    var modelNameMap = new HashMap<String, String>()

    modelNameMappings = modelNameMap

    var importMap = new HashMap<String, String>()

    importMappings = importMap
}

sourceSets {
    main {
        java {
            srcDir "${buildDir}/generated/src/gen/java"
        }
    }
}

sourceSets {
    main {
        java {
            srcDir(generatedOpenApiSrcDir)
        }
    }
}

tasks.openApiGenerate {
    doLast {
        delete(files("${buildDir}/generated/src/main/java/kasanari/catalog/paimon/api/impl"),)
    }
}

// TODO: fix generation for paimon
//tasks.compileJava {
//    dependsOn(tasks.openApiGenerate)
//}