dependencies {
    implementation project(':modules:catalog:catalog-iceberg-core')
    implementation project(':modules:catalog:catalog-iceberg-common')
    implementation libs.iceberg.nessie

    testImplementation libs.testcontainers.core
    testImplementation libs.testcontainers.nessie

    testImplementation testFixtures(project(':modules:catalog:catalog-iceberg-core'))
    testImplementation testFixtures(project(':modules:fixtures:fixtures-s3'))
}