dependencies {
    implementation project(':modules:catalog:catalog-iceberg-core')
    implementation libs.iceberg.nessie
    implementation libs.hadoop3.common

    testImplementation libs.testcontainers.core
    testImplementation libs.testcontainers.nessie

    testImplementation testFixtures(project(':modules:catalog:catalog-iceberg-core'))
}