package kasanari.instrumentation.spi.lance;

public enum LanceCatalogOperation {
    CREATE_NAMESPACE,
    DESCRIBE_NAMESPACE,
    DROP_NAMESPACE,
    LIST_NAMESPACES,
    LIST_TABLES,
    NAMESPACE_EXISTS,
    ALTER_TABLE_ALTER_COLUMNS,
    ALTER_TABLE_DROP_COLUMNS,
    ALTER_TABLE_ADD_COLUMNS,
    CREATE_TABLE,
    DECLARE_TABLE,
    DEREGISTER_TABLE,
    DESCRIBE_TABLE,
    DROP_TABLE,
    REGISTER_TABLE,
    RENAME_TABLE,
    RESTORE_TABLE,
    TABLE_EXISTS
}
