services:
  catalog-storage:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  nessie:
    image: ghcr.io/projectnessie/nessie:0.104.3
    ports:
      - "19120:19120"
    depends_on:
      - catalog-storage
    environment:
      JAVA_OPTS_APPEND: "-Dnessie.version.store.type=JDBC -Dquarkus.datasource.username=postgres -Dquarkus.datasource.password=postgres -Dquarkus.datasource.jdbc.url=jdbc:postgresql://catalog-storage:5432/postgres"
